apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes:
  - name: host-volume
    persistentVolumeClaim:
      claimName: pvc-hostpath
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c","echo '<h1>Hello Kubernetes<h1>' > /mydata/pawan"]
    volumeMounts:
    - name: host-volume
      mountPath: /mydata
